version: '3'

networks:
  mapNet:
    driver: bridge
services:
  nginxphp:
    build: ./
    image: mapapi
    restart: always
    container_name: mapapi_app
    depends_on:
      - mariadb
    links:
      - "mariadb"
    networks:
      - mapNet
    volumes:
      - ./html:/var/www/html
      - /etc/letsencrypt/archive/stories282.shop/:/letsencrypt
    ports:
      - "80:80"
      - "443:443"
  mariadb:
    image: mariadb:10.5.8
    networks:
      - mapNet
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - TZ=Asia/Seoul
    volumes:
      - ./db:/var/lib/mysql